server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: 'amigoscode'
    url: jdbc:postgresql://localhost:5444/customer
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true