services:
  postgres-customer:
    container_name: postgres-customer
    image: postgres:16.1
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres-customer
    volumes:
      - postgres-customer:/data/postgres-customer
    ports:
      - "5444:5432"
    networks:
      - postgres-microservices
    restart: unless-stopped

  postgres-fraud:
    container_name: postgres-fraud
    image: postgres:16.1
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres-fraud
    volumes:
      - postgres-fraud:/data/postgres-fraud
    ports:
      - "5443:5432"
    networks:
      - postgres-microservices
    restart: unless-stopped

  postgres-notification:
    container_name: postgres-notification
    image: postgres:16.1
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres-notification
    volumes:
      - postgres-notification:/data/postgres-notification
    ports:
      - "5442:5432"
    networks:
      - postgres-microservices
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-microservices
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin-microservices
    ports:
      - "5051:80"
    networks:
      - postgres-microservices
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  eureka-server:
    image: hugodiaz/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - zipkin

  apigw:
    image: hugodiaz/apigw:latest
    container_name: apigw
    ports:
      - "8083:8083"
    depends_on:
      - zipkin
      - eureka-server

networks:
  postgres-microservices:
    driver: bridge

volumes:
  postgres-customer:
  postgres-fraud:
  postgres-notification:
  pgadmin: