apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      name: notification
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: hugodiaz/notification:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
            - name: SPRING_DATASOURCE_USERNAME
              value: doadmin
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://notification-database-amigoscode-do-user-15983897-0.c.db.ondigitalocean.com:25060/notification
            - name: SPRING_DATASOURCE_PASSWORD
              value: AVNS_gV9lSjdqcf0Z3rET98e
      restartPolicy: Always
